import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CYC Racing App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <a href="https://cyc.pe.ca/" target="_blank" rel="noreferrer" className="ml-6">
      <Image src="/logo.png" width={175} height={100} alt="cyc logo" className=""/>
      </a>
        <h1 className={styles.title}>
         CYC Racing App
        </h1>

        

        <Link href={"/race"}>
          <button className="btn btn-info mt-6">Time a Race</button>
        </Link>
        <Link href={"/course-list"}>
          <button className="btn btn-info mt-6">Course List</button>
        </Link>
      </main>
    </div>
  );
}
